server:
  port: ${PORT:7501}

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:mem:account_db
    driver-class-name: org.h2.Driver
    username: account
    password: account
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    disable-swagger-default-url: true