server:
  port: ${PORT:7500}

spring:
  application:
    name: atm-service
  datasource:
    url: jdbc:h2:mem:atm_db
    driver-class-name: org.h2.Driver
    username: atm
    password: atm
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

account-api-url: http://localhost:7501

springdoc:
  swagger-ui:
    disable-swagger-default-url: true